[package]
name = "wasminspect"
version = "0.1.0"
authors = ["Yuta Saito <kateinoigakukun@gmail.com>"]
edition = "2018"

[[bin]]
name = "wasminspect"
path = "src/main.rs"

[dependencies]
wasminspect-cli = { path = "crates/cli" }
wasminspect-core = { path = "crates/core" }
wast-spec = { path = "crates/wast-spec" }
clap = "2.33.0"
wasmi-validation = "0.3.0"
