[package]
name = "wasminspect-cli"
version = "0.1.0"
authors = ["Yuta Saito <kateinoigakukun@gmail.com>"]
edition = "2018"

[dependencies]
wasminspect-core = { path = "../wasminspect-core" }
wasmi-validation = "0.3.0"