[package]
name = "wasminspect-wasi"
version = "0.1.0"
authors = ["Yuta Saito <kateinoigakukun@gmail.com>"]
edition = "2018"

[dependencies]
wasminspect-vm = { path = "../vm" }
wasminspect-api = { path = "../api" }
wasi-common = "0.8.0"
parity-wasm = "0.41"
