name: Check
on: [push, pull_request]
jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Checkout submodules
        shell: bash
        run: |
          auth_header="$(git config --local --get http.https://github.com/.extraheader)"
          git submodule sync --recursive
          git -c "http.extraheader=$auth_header" -c protocol.version=2 submodule update --init --force --recursive --depth=1
      - name: Install wabt and fixtures
        run: make .wabt fixtures
      - name: Run cargo build
        uses: actions-rs/cargo@v1.0.1
        with:
          command: build
      - name: Run cargo test 
        uses: actions-rs/cargo@v1.0.1
        with:
          command: test
